version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-246-92-116.eu-west-1.compute.amazonaws.com
            database: d63l9ufnae6753
            user: zqrkedfpuhcmpl
            password: 6ea07aeb2703de515cd2a14b1a0cade1caf169de2647695007009ab8cb158261
            # rawAccess: true
            port: '5432'
            migrations: true
            ssl: true
